name: Test Workflow
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test01
        run: echo "success"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: tag01
        run: echo "deployed"      